### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#11]
**User Story**
As a repository maintainer, I'd like for the privacy policy to accurately reflect the data usage of the project, so that users are properly informed about how their data is used.

**Acceptance Criteria**
- The privacy policy is relevant to this project and uses its name (*Roll For Reaction*, not *React RPG*)
- The privacy policy has undergone review, and any statements not relevant to *Roll For Reaction* have been removed

**Notes**

**Comment by Pyxxil** [comment]
The first thing to determine is whether or not we need to use react-ga, as it's Google Analytics. I'll have a look into if I can determine why it was added upstream.

**Comment by Pyxxil** [comment]
So, browsing through the history for package.json shows that react-ga was added in 994840e5cea037328f39b3a87fd550291b9641a4 upstream. From what I can tell, this simply registers that the page was opened.

In our branch, it was removed from everything but package.json in d4f5a813ef34e33acee30a570386112446dccff8.

I'll build it locally without react-ga in package.json to see if it's possible to remove completely. If so, as far as I'm aware that's the only item of ours that is privacy related. That may change if we decide to store anything server side regarding multiplayer.
