### ISSUE TITLE
Update game instructions

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#128]
**User Story**
As a gamer, I'd like to to know what the commands are, so that I'm able to play better

**Acceptance Criteria**

- The game instructions screen shows all hotkeys

**Comment by Pyxxil** [comment]
We need to have a discussion around what we should actually do with this. We don't have the assets for other keys, so we'd either need to find them, create our own, or just use text instead.

We should also think about how many key-binds we will have, how many the player needs to know about, and whether this should be in a separate document (i.e. the tutorial document), or if we want the instructions to potentially span multiple dialogs.
