### ISSUE TITLE
 Race and Class starting items

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#132]
**User Story**
As a gamer, I'd like the races and classes to give different starting items, so that it feels more unique.

**Acceptance Criteria**

- The race and class you choose will give you starting items according to the wiki (along with or instead of the rusty sword)

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
Class and race don't change much

**Describe the solution you'd like**
The race and class you choose will give you starting items according to the wiki (along with or instead of the rusty sword)

**Comment by Frosty273** [comment]
For clarification, I believe the race affects your starting ability scores and the class affects your starting items.

**Comment by Matteas-Eden** [comment]
It doesn't seem that there are sufficient items in the game to support this issue. Perhaps a separate issue for adding those items would be better, so that they can then be allocated to class afterwards?
