### ISSUE TITLE
Add ability to open/close all menus with the keyboard

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#159]
**User Story**
As a game designer, I'd like to allow the user to open and close menus via the keyboard in addition to the mouse.

**Acceptance Criteria**

- All menus accept `ENTER` to open
- All menus accept `ESCAPE` to close

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
I'm always frustrated when switching from keyboard to mouse purely to open/close a menu, when some menus do not require mouse to open/close.

**Describe the solution you'd like**
* The shop menu should accept `ENTER` to open the shop and view items. 
* The settings menu should accept `ENTER` to return to the main menu
* The ability dialog and inventory dialogs should accept `ESCAPE` to exit the menus
* The settings menu should accept `ESCAPE` to close the menu
* Confirmation menus should accept `ENTER` for 'yes' and `ESCAPE` for 'no'

**Comment by Pyxxil** [comment]
> The ability dialog and inventory dialogs should accept ESCAPE to exit the menus

Do you want the ability dialog to save any changes if the user presses ESCAPE?

**Comment by Matteas-Eden** [comment]
> 
> 
> > The ability dialog and inventory dialogs should accept ESCAPE to exit the menus
> 
> Do you want the ability dialog to save any changes if the user presses ESCAPE?

Ideally, the information would be saved unless they change their race. But it's a nice-to-have, not a must.

**Comment by Pyxxil** [comment]
> Ideally, the information would be saved unless they change their race. But it's a nice-to-have, not a must.

How would they change their race? This is dealing with the ability dialog after the start.

**Comment by Matteas-Eden** [comment]
> 
> 
> > Ideally, the information would be saved unless they change their race. But it's a nice-to-have, not a must.
> 
> How would they change their race? This is dealing with the ability dialog after the start.

Oh, my apologies - I thought you mean the ability dialog at the start of the game. For opening the ability dialog during the game, I don't think changes should be saved on exit unless they press 'CONFIRM' or `ENTER`.

**Comment by Pyxxil** [comment]
Do we want 'ESC' to open the settings Dialog if pressed when nothing else is open?

**Comment by Matteas-Eden** [comment]
> 
> 
> Do we want 'ESC' to open the settings Dialog if pressed when nothing else is open?

I think that would be a nice quality of life addition.
