### ISSUE TITLE
Customise character colour not working

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#182]
**Bug Summary**

When on the customise character page, the colour things don't change the character sprite.  

---

**Expected behavior**

The character sprite to change colour

**Observed Behaviour**

The character sprite did not change colour

**Steps To Reproduce**

1. Open roll for reaction in Edge
2. Go to the character creation page
3. Change the colours

**Environment**
- Version: 8f8f093
- OS: Windows 10
- Browser: Microsoft Edge 44.18362.449.0

---

**Screenshots**
![image](https://user-images.githubusercontent.com/45865186/80674544-4f04ca00-8b06-11ea-922e-3e6733d0936f.png)

**Comment by Matteas-Eden** [comment]
This appears to be an issue with [react-color](https://github.com/casesandberg/react-color).
