### ISSUE TITLE
Restrict player's defence value to be a positive number

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#184]
**User Story**
As a game designer, I'd like for a player's defence value to not fall below 0.

**Acceptance Criteria**

- Player's defence value cannot be negative and has a minimum of 0
- The defence value given by dexterity modifier is `dex_ability_modifier + 1` for non-negative values

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
I don't want the player to be severely disadvantaged at a low dexterity score.

**Describe the solution you'd like**
The bonus to defence given by dexterity is rescaled to follow the below:
`defence_bonus = dex_ability_modifier >= 0 ? dex_ability_modifier + 1 : 0`

**Comment by Frosty273** [comment]
The implementation of the the formula causes the following issues:

- If `dex_ability_modifier = -1`, then `defence_bonus = 0`
- If `dex_ability_modifier = 0`, then `defence_bonus = 0`
- If `dex_ability_modifier = 1`, then `defence_bonus = 2`

Therefore, would it be more ideal for the check to be `dex_ability_modifier >= 0`?

**Comment by Matteas-Eden** [comment]
That's absolute right @Frosty273, my apologies. It should be `>= 0`, and the fact that it wasn't written like that originally can be considered a typo. My apologies for the confusion. I'll update the issue.
