### ISSUE TITLE
Add more tiers

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#187]
**User Story**
As a player, I'd like to have more tiers, so that leveling up feels more worth it.

**Acceptance Criteria**

- There are more than just 2 tiers allowing when you will get an item
- This applies to both the shop and the chests

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

There are only two tiers

**Describe the solution you'd like**
For there to be more tiers (or something similar allowing for more varied distribution of items)

**Comment by Matteas-Eden** [comment]
I think this should tie in with #49, as they are closely related.
