### ISSUE TITLE
Implement different enemy attacks

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#191]
**User Story**
As a player character, I'd like enemies to have different attacks, so that I encounter different styles of enemies making the game more varied

**Acceptance Criteria**

- Enemies have other attacks other than just walking up to you and hitting you

**Notes**
Ideas:
- Ranged attack
- Suicide bomber (if they get to you before you kill then, you take damage - fighter would use a shield)
- Shoot in all directions
- Teleport
- Temporarily invisible
- Heal themselves/heal another monster
- Ghost that can fly through walls
- Poisonous (take damage over a range of turns)
- Paralyse you (you can't move/attack for a turn)

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

All enemies have the same attack

**Describe the solution you'd like**

Enemies to have different attack styles

**Comment by Pyxxil** [comment]
Probably relies on #154 being completed first.
