### ISSUE TITLE
Balance game elements

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#205]
**User Story**
As a Libra, I'd like to the game to be balanced, so that it everyone can play more nicely and more fairly.

**Acceptance Criteria**

- No matter which race/class you start with, the game is no easier/harder
- No matter which abilities you pour your points into (or don't pour your points into), the game is no easier/harder
- The prices of the items are balanced
- It is possible to obtain any one item in a playthrough (i.e. if an item has a level prerequisite, it should be possible for the player to obtain that level)
- Item stats provide a fair and reasonable experience in accordance with the strength of enemies

**Comment by Pyxxil** [comment]
This has turned into more of a recurring theme than a singular issue.
