### ISSUE TITLE
Add Beautiful Logo to README

### ISSUE THREAD

**Issue by Pyxxil** [Matteas-Eden/roll-for-reaction#21]
**User Story**
As a User, I would like to see the logo that exists for the project to be displayed in the README for the project.

**Acceptance Criteria**

- [x] Add the logo to the README 

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
We have a beautiful logo, and it would be pointless if we don't use it somewhere. Adding it to the README would be a good start.

**Describe the solution you'd like**
Add a section to the README that displays the beautiful logo we have.

**Comment by Matteas-Eden** [comment]
Just a note that the README for `gh-pages` branch needs to be updated separately, since for the time being (until #7 is closed) it acts as a project info page.

**Comment by Matteas-Eden** [comment]
Also, when adding the logo to the README you can use a link to GitHub's hosting of the file instead of referencing the file on the repo.

Like this: `![logo](https://user-images.githubusercontent.com/45865186/77014224-a9265180-69d6-11ea-92d3-18af1d76c740.png)`
