### ISSUE TITLE
Journal slowing down game

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#225]
**Bug Summary**

When you've been playing for a long time, the journal becomes so giant it actually slows down the game

**Test Case(s)**

Play through to  a high level

---

**Expected behavior**

You to be able to keep playing as normal

**Observed Behaviour**
The journal gets so heavy it slows down the game

**Steps To Reproduce**

1. Checkout the maps branch (or master if it's been merged)
2. Try playing till level 25
3. You will notice the game starts to get slower as the journal becomes overloaded

**Environment**
- Version: Maps branch
- OS: Windows 10
- Browser: Microsoft Edge

**Comment by Pyxxil** [comment]
I'll also add in the toggling of the journal even in side view.
