### ISSUE TITLE
Make boss room smaller

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#233]
**User Story**
As someone who doesn't like hide and seek, I'd like to be stopped by the boss and not have to search through the boss room for it, so that I don't feel like the boss is hiding from me

**Acceptance Criteria**

- The rooms are smaller
- Monsters are moved to stay in the rooms
- Stairs have one space around them

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

It can be hard to find the bosses in the rooms and too easy to walk past them

**Describe the solution you'd like**

Harder to just walk past without even seeing them

**Comment by Frosty273** [comment]
![Capture](https://user-images.githubusercontent.com/39424472/82142869-b7d49c00-9893-11ea-90a0-1b2a4a21be49.PNG)
Adjust layout of chests in top left corner room on floor 2-4.
