### ISSUE TITLE
Make swords more powerful

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#237]
**User Story**
As a fighter, I'd like to my swords to be more powerful, so that they're not useless compared to the ranged weapons

**Acceptance Criteria**

- Swords are slightly more powerful

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

It's pointless to get swords when you have the ranged weapons

**Describe the solution you'd like**

Swords to do more damage

**Comment by Matteas-Eden** [comment]
It seems that #242 was meant to close the issue, but a typo in the PR description meant it wasn't linked properly. As such, I'm manually closing this issue has it has been resolved by that PR.
