### ISSUE TITLE
Format items displayed in shop

### ISSUE THREAD

**Issue by Frosty273** [Matteas-Eden/roll-for-reaction#246]
**User Story**
As a game designer, I'd like to organised the shop inventory, so that similar item types are listed together.

**Acceptance Criteria**

- Shop inventory is reordered

**Notes**

Blocked until #242 is merged containing new items.

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

Pages in the shop display a mixture of weapons and armor on a page

**Describe the solution you'd like**

Similar items like all leather gear are displayed together on the same page.

**Comment by Pyxxil** [comment]
Is this related to #186?

**Comment by Frosty273** [comment]
Partially, yes

**Comment by Pyxxil** [comment]
Closed as was meant to be closed with #255
