### ISSUE TITLE
Play the Game

### ISSUE THREAD

**Issue by Pyxxil** [Matteas-Eden/roll-for-reaction#267]
**User Story**
As a Student in the course CS732/SE750, I would like to make sure that my lecturers get to see what our project involves first hand.

**Acceptance Criteria**
- Play the game
- (Optional) Complete the game
- Grade our Project

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
As a student, I always prefer it when my lecturers give me advice on my projects. I also think it's a good way to determine grades.

**Describe the solution you'd like**
I would like the lecturers to play the game and to mark us based on our project.

**Comment by andrew-meads** [comment]
Hmmmm.... Are you REALLY sure you'd like me to actually give you marks? "passing courses" is so overrated you know...

**Comment by Pyxxil** [comment]
> Hmmmm.... Are you REALLY sure you'd like me to actually give you marks? "passing courses" is so overrated you know...

Well, if we don’t pass the course we could always create a bug report and make a PR to fix it later.

**Comment by Matteas-Eden** [comment]
The completion of the course and the subsequent release of grades by @andrew-meads means that this issue can now be closed.
