### ISSUE TITLE
Implement DnD ability scores/modifiers

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#29]
**User Story**
As a designer, I'd like to implement the ability scores from *Dungeons and Dragons*, so that the game realises its vision as described in `VISION.md`.

**Acceptance Criteria**

- ATK and DEF stats removed
- Ability scores implemented
- Ability modifiers implemented
- UI adjusted accordingly

**Notes**

Refer to `VISION.md` for details on ability scores and modifiers.

To calculate ability modifier: `AM = floor((AS - 10) / 2)`

Prototype:

![RollForReactionUIBar](https://user-images.githubusercontent.com/45587386/77208027-c5092f00-6b5f-11ea-8ac6-40371979f0c1.PNG)

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
This feature is required as per the table on the README.

**Describe the solution you'd like**
I would like all of the ability scores (STR, CON, INT, WIS, CHR, DEX) implemented for the player character and represented appropriately on the UI.

**Comment by Frosty273** [comment]
Add 6 ability scores field scores into UI.
STR will display attack and CON will display defense temporarily.
Numbers can be randomized for the other 4 fields.
