### ISSUE TITLE
Edit key mapping

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#33]
**User Story**
As a user, I'd like to be the key for attack to be different to continue, so that I don't accidentally skip the notifications.

**Acceptance Criteria**

- The attack key will either be permanently mapped to, or have a setting of being mapped to, a different key than continue

**Comment by Matteas-Eden** [comment]
@all-contributors please add @KimberleyEvans-Parker  for ideas
