### ISSUE TITLE
Stop new item notification blocking inventory management

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#39]
**User Story**
As a player, I'd like to be able to equip an item as soon as I receive it.

**Acceptance Criteria**

- New item notification does not prevent player from opening inventory and equipping item

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
I'm always frustrated when I receive an item but I have to wait for the notification to go away before I can equip it.

**Describe the solution you'd like**
Either the notification shows up somewhere else, or there's an alternative way of opening the inventory screen.

**Comment by KimberleyEvans-Parker** [comment]
Another option is the notification has an 'equip' button
