### ISSUE TITLE
Update README with  project overview

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#5]
**User Story**
As a contributor, I'd like to have a README which gives a comprehensive overview of the project, so that those who look at the repository have a good understanding of its purpose and what if offers.

**Acceptance Criteria**

- README is updated with relevant information

**Notes**

**Comment by Pyxxil** [comment]
We should also add in simple installation steps, as that's part of the Peer Review process:
> Are installation / configuration instructions provided and can they be easily followed?
