### ISSUE TITLE
Choose class and race

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#50]
**User Story**
As a gamer, I'd like to be able to choose a race and class, so that I have more choice in this rpg.

**Acceptance Criteria**

- User can choose their race
- User can choose their class

**Notes**

Linked to character name creation issue #45 

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
Roll for Reaction does not have enough rpg elements.

**Describe the solution you'd like**
Planned race choices: 
 - Human
 - Elf
 - Dwarf

Planned class choices:
 - Warrior
 - Wizard
 - Ranger

**Comment by Matteas-Eden** [comment]
Upon further investigation, I think this, #46, and #45 will all end up affecting the same sets of files.
