### ISSUE TITLE
Implement CHA - Charisma

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#56]
**User Story**
As a game designer, I'd like a player's charisma score/modifier to affect the prices they receive when in the shop.

**Acceptance Criteria**

- High charisma modifiers (+1 and above) lower the price of items in the shop
- Low charisma modifiers (-1 and below) raise the price of items in the shop

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
Currently the charisma score does not affect any gameplay elements, but it should affect some.

**Describe the solution you'd like**
Based on the charisma ability modifier (which itself is affected is by ability score), the prices a player should see at the shop should change. In particular, the following equation is proposed:

Buy Price: `base_price * (1.0 - ability_bonus / 10)`
Sell Price: `base_price * (0.5 + ability_bonus / 10)`

**Use Case**
Health potions cost 15 Gold. Player A has 12 CHA (modifier of +1). Player B has 8 CHA (modifier of -1).

A -
    Buy: `15 * (1 - 1 / 10) = 15 * 0.9 = 13.5`
    Sell: `15 * (0.5 + 1 / 10) = 15 * 0.6 = 9`

B -
    Buy: `15 * (1 - (-1) / 10) = 15 * 1.1 = 16.5`
    Sell: `15 * (0.5 + (-1) / 10) = 15 * 0.4 = 5`

**Comment by Pyxxil** [comment]
Would this also effect sale price back to the shop?

**Comment by Matteas-Eden** [comment]
> Would this also effect sale price back to the shop?

In the current implementation, the sell price is `buy_price / 2`, so it would affect the sell price. However, that would then be counterintuitive. I think the sell price should probably be changed, but I'm not sure how it should be changed. Keen to hear your thoughts.
