### ISSUE TITLE
Host game using GitHub Pages

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#7]
**User Story**
As a QA tester, I'd like to be able to access the game online, so that it can be tested, played and enjoyed more easily.

**Acceptance Criteria**

- Game is hosted and playable at `matteas.nz/roll-for-reaction`

**Notes**
- The `README.md` is currently viewable at [matteas.nz/softeng-750-react-rpg](https://matteas.nz/softeng-750-react-rpg)

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**

I don't like the requirement to build the code from source simply to play/test the game.

**Describe the solution you'd like**

I want our version of the game to be playable online, in a similar manner to the original.

**Comment by Pyxxil** [comment]
This is something only you can do:
https://github.com/gitname/react-gh-pages

**Comment by Matteas-Eden** [comment]
I know only I can do it - that's why I've assigned myself to the issue.
