### ISSUE TITLE
Centered Chest [Low Priority]

### ISSUE THREAD

**Issue by KimberleyEvans-Parker** [Matteas-Eden/roll-for-reaction#82]
**User Story**
As someone with OCD, I'd like a chest to be centered, so that it looks nicer.

**Acceptance Criteria**

- The chest is centered

**Notes**
![bug4](https://user-images.githubusercontent.com/45865186/78513995-394ffd80-7803-11ea-9ed0-4b0f042082f3.PNG)

**Comment by Frosty273** [comment]
What floor is this on?
