### ISSUE TITLE
Implement INT - Intelligence

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/roll-for-reaction#99]
**User Story**
As a game designer, I'd like a player's intelligence ability score to affect the amount of mana they have available.

**Acceptance Criteria**

- A player's mana pool is determined by their intelligence ability bonus

**Notes**

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
Currently, the player's intelligence ability score/modifier does not affect any gameplay elements.

**Describe the solution you'd like**
The player's mana pool is determined by their intelligence ability score/modifier. The following calculation is proposed:

`(ability_bonus > 0) ? ability_bonus * 10:0`

**Use Case**
Player A has 14 INT (modifier of +2). Player B has 8 INT (modifier of -1). Player C has 20 INT (modifier of +5).

A: `2 > 0 === true, so 2 * 10 = 20`
B: `-1 > 0 === false, so 0`
C: `5 > 0 === true, so 5 * 10 = 50`

**Comment by Frosty273** [comment]
So according to the calculation, the modifier is used to determine the mana pool, so if INT is less then 12, is the mana pool 0/0? Or is the calculation added onto the base max mana in which case what would be the starting mana pool value then?

**Comment by Matteas-Eden** [comment]
> So according to the calculation, the modifier is used to determine the mana pool, so if INT is less then 12, is the mana pool 0/0? Or is the calculation added onto the base max mana in which case what would be the starting mana pool value then?

The former is correct (no base mana pool), but now that you raise the issue I don't think 12 should be the minimum intelligence to have a mana pool. The calculation should then be modified to be:

`(ability_bonus >= 0) ? (ability_bonus + 1)  * 10:0`

In which case a player with 10/11 intelligence has 10 mana, a player with 12/13 intelligence has 20 mana and so forth.
